WebApp_Inventory/Controllers/FormaVentaController.cs
using Microsoft.AspNetCore.Mvc;
using Persistencia.Entities;
using System.Text.Json;

namespace WebApp_Inventory.Controllers;

public class FormaVentaController : Controller
{
    private static string? _baseUrl;//varibale que almacena el endpoint de la API que se va a consumir

    private JsonSerializerOptions options = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,//agregado la sintaxis camelcase al los JSON que se devuelen de la API
    };

    //constructor del controlador
    public FormaVentaController()
    {
        var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();//configurando la variable de conreuccion para que cuando se cree el controler obtenga el archivo de cofiguracion
        _baseUrl = builder.GetSection("ApiSetting:baseUrl").Value;//obteniendo el endpoint de la API desde el archivo de configuracion 
    }

    public IActionResult Listar()
    {
        List<Forma_Venta> lista = new List<Forma_Venta>();//lista del modelo Forma_Venta que se va a llenar con los datos de la API


        var client = new HttpClient();//cliente http para consumir la API
        client.BaseAddress = new Uri(_baseUrl);//endpoint como parametro
        var response = client.GetAsync("/Forma_Venta");
        if (response.Result.IsSuccessStatusCode)
        {
            var json_respuesta = response.Result.Content.ReadAsStringAsync().Result;
            var resultado = JsonSerializer.Deserialize<List<Forma_Venta>>(json_respuesta, options);
            lista = resultado ?? new List<Forma_Venta>();
        }

        return View(lista);
    }


    //crear una Nueva Forma de Venta
    public IActionResult Crear()
    {
        return View();
    }


    [HttpPost]
    public IActionResult Crear(Forma_Venta objForma)
    {
       
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);

        var response = client.PostAsJsonAsync("/Forma_Venta", objForma);

        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {
            var mensajeError = response.Result.Content.ReadAsStringAsync().Result;
            ViewBag.MensajeError = mensajeError;
           
        }
        return View();
    }

    //editar una Forma de Venta
    public IActionResult Editar(int id)
    {
        Forma_Venta ob = new Forma_Venta();

        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.GetAsync($"/Forma_Venta/{id}");
        if (response.Result.IsSuccessStatusCode)
        {
            var json_respuesta = response.Result.Content.ReadAsStringAsync().Result;
            //Deserializando el objeto JSON a un objeto Tipo_Producto
            var objForma = JsonSerializer.Deserialize<Forma_Venta>(json_respuesta, options);
            ob = objForma ?? new Forma_Venta();
        }
        return View(ob);
    }

    [HttpPost]
    public IActionResult Editar(Forma_Venta objForma)
    {
       
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.PutAsJsonAsync($"/Forma_Venta/{objForma.id_FormaVenta}", objForma);
        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {
            return View();
        }
      
    }

    //eliminar una Froma de Venta
    public IActionResult Eliminar(int id)
    {
        Forma_Venta ob = new Forma_Venta();

        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.GetAsync($"/Forma_Venta/{id}");
        if (response.Result.IsSuccessStatusCode)
        {
            var json_respuesta = response.Result.Content.ReadAsStringAsync().Result;

            //Deserializando el objeto JSON a un objeto Tipo_Producto
            var objForma = JsonSerializer.Deserialize<Forma_Venta>(json_respuesta, options);
            ob = objForma ?? new Forma_Venta();
        }
        return View(ob);
    }

    [HttpPost]
    public IActionResult Eliminar(Forma_Venta objForma)
    {
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.DeleteAsync($"/Forma_Venta/{objForma.id_FormaVenta}");
        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {
            var mensajeError = response.Result.Content.ReadAsStringAsync().Result;
            ViewBag.MensajeError = mensajeError;
            
        }
        return View();
    }
}

WebApp_Inventory/Controllers/TipoProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Persistencia.Entities;
using System.Text.Json;

namespace WebApp_Inventory.Controllers;

public class TipoProductoController : Controller
{
    private static string? _baseUrl;//variable que recibira la url de la api desde appsettings

    private JsonSerializerOptions options = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public TipoProductoController()//desde el momento de su construccion
    {
        var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
        _baseUrl = builder.GetSection("ApiSetting:baseUrl").Value;
    }

    //listar tipos de Productos desde la API
    public IActionResult Listar()
    {
        List<Tipo_Producto> lista= new List<Tipo_Producto>();


        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.GetAsync("/Tipo_Producto");
        if (response.Result.IsSuccessStatusCode)
        { 
            var json_respuesta= response.Result.Content.ReadAsStringAsync().Result;
            var resultado= JsonSerializer.Deserialize<List<Tipo_Producto>>(json_respuesta,options);
            lista = resultado ?? new List<Tipo_Producto>();
        }

        return View(lista);
    }

    //crear un nuevo tipo de producto
    public IActionResult Crear()
    {
        return View();
    }


    [HttpPost]
    public IActionResult Crear(Tipo_Producto objTipo)
    {
        
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);

        var response = client.PostAsJsonAsync("/Tipo_Producto", objTipo);

        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {
            return View();
        }
      
           
       
    }


    //editando un tipo de producto
    public IActionResult Editar(int id)
    { 
        Tipo_Producto ob = new Tipo_Producto();

        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.GetAsync($"/Tipo_Producto/{id}");
        if (response.Result.IsSuccessStatusCode)
        {
            var json_respuesta = response.Result.Content.ReadAsStringAsync().Result;
            //Deserializando el objeto JSON a un objeto Tipo_Producto
            var objTipo = JsonSerializer.Deserialize<Tipo_Producto>(json_respuesta,options);
            ob= objTipo ?? new Tipo_Producto();
        }
        return View(ob);
    }

    [HttpPost]
    public IActionResult Editar(Tipo_Producto objTipo)
    {
       
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.PutAsJsonAsync($"/Tipo_Producto/{objTipo.id_TipoProducto}", objTipo);
        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {
            return View();
        }
        
    }

    //eliminar un tipo de producto
    public IActionResult Eliminar(int id)
    {
        Tipo_Producto ob = new Tipo_Producto();

        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.GetAsync($"/Tipo_Producto/{id}");
        if (response.Result.IsSuccessStatusCode)
        {
            var json_respuesta = response.Result.Content.ReadAsStringAsync().Result;
            //Deserializando el objeto JSON a un objeto Tipo_Producto
            var objTipo = JsonSerializer.Deserialize<Tipo_Producto>(json_respuesta, options);
            ob = objTipo ?? new Tipo_Producto();
        }
        return View(ob);
    }

    [HttpPost]
    public IActionResult Eliminar(Tipo_Producto objTipo)
    {
        var client = new HttpClient();
        client.BaseAddress = new Uri(_baseUrl);
        var response = client.DeleteAsync($"/Tipo_Producto/{objTipo.id_TipoProducto}");
        if (response.Result.IsSuccessStatusCode)
        {
            ViewBag.Exito = true; // se guardo correctamente
            ModelState.Clear();   //se limpia el modelo para que no se repita el mensaje de exito
            return View();
        }
        else
        {

            var mensajeError = response.Result.Content.ReadAsStringAsync().Result;
            ViewBag.MensajeError = mensajeError;
        }
        return View();

    }
}

WebApp_Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css" />
    <link href="~/styles/sb-admin-2.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp_Inventory.styles.css" asp-append-version="true" />

    <link href="~/inventory-control.ico" rel="icon" type="image/x-icon" />

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
</head>

<body id="page-top">

    <div id="wrapper" class="d-flex">
        <!-- Sidebar -->
        
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <li class="nav-item">

                <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-boxes"></i>
                    </div>

                    <div class="sidebar-brand-text mx-3">INVENTRACK</div>
                </a>
            </li>

            <li class="nav-item">

                <a class="nav-link collapsed" href="#"
                   data-bs-toggle="collapse"
                   data-bs-target="#collapseInventario"
                   aria-expanded="false"
                   aria-controls="collapseInventario">
                    <i class="fas fa-warehouse"></i>
                    <span>ALMACEN</span>
                    <span class="caret"></span>
                </a>
                <div id ="collapseInventario" class="collapse" data-bs-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-area="" asp-controller="TipoProducto" asp-action="Listar">
                            Tipos de Productos
                        </a>
                        <a class="collapse-item" asp-area="" asp-controller="FormaVenta" asp-action="Listar">
                            Formas de Ventas
                        </a>
                        <a class="collapse-item" asp-area="" asp-controller="Producto" asp-action="Listar">
                            Stock De Productos
                        </a>
                    </div>
                </div>
            </li>



        </ul>

        
        <div id="content-wrapper" class="d-flex flex-column min-vh-100">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar (si deseas agregar uno) -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Puedes dejar vacío o colocar botones de usuario, notificaciones, etc. -->
                </nav>

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- End Page Content -->

            </div>
            <!-- End Main Content -->
        </div>
        <!-- End Content Wrapper -->

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/sb-admin-2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>